#!/usr/bin/env python

"""Run pylint without the sandbox in the PYTHONPATH."""

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import os
import subprocess
import sys


def filter_path(paths):
    yam_root = os.getenv('YAM_ROOT')
    if yam_root:
        yam_root = os.path.realpath(yam_root)
        for name in paths:
            if not os.path.realpath(name).startswith(yam_root):
                yield name
    else:
        for name in paths:
            yield name


def main():
    env = os.environ.copy()
    # if 'PYTHONPATH' in env:
    #     env['PYTHONPATH'] = ':'.join(filter_path(env['PYTHONPATH'].split(':')))
    env['PYTHONPATH'] = ''

    return subprocess.call(['pylint'] + sys.argv[1:], env=env)


if __name__ == '__main__':
    sys.exit(main())
